version: '3'
services:
  db:
    image: mysql:latest
    container_name: local-mysql-fast-campus
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=forumapp
    volumes:
      - D:\\study\\golang\\fastcampus\\golang 6 project\\forumapp_mysql/db:/var/lib/mysql